// <auto-generated />
using System;
using CampusLostFound.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CampusLostFound.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CampusLostFound.Api.Models.LostFoundItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("DateReported")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("LostFoundItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Accessories",
                            ContactEmail = "alex.chen@example.edu",
                            ContactName = "Alex Chen",
                            DateReported = new DateOnly(2026, 8, 10),
                            Description = "Small black leather wallet with a few cards inside.",
                            Location = "Library",
                            Status = "ACTIVE",
                            Title = "Black Wallet",
                            Type = "LOST"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Personal Items",
                            ContactEmail = "priya.nair@example.edu",
                            ContactName = "Priya Nair",
                            DateReported = new DateOnly(2026, 8, 11),
                            Description = "Blue metal water bottle with a dented cap.",
                            Location = "Cafeteria",
                            Status = "ACTIVE",
                            Title = "Blue Water Bottle",
                            Type = "FOUND"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Documents",
                            ContactEmail = "jordan.lee@example.edu",
                            ContactName = "Jordan Lee",
                            DateReported = new DateOnly(2026, 8, 12),
                            Description = "University ID card, name partially visible.",
                            Location = "Computer Lab",
                            Status = "ACTIVE",
                            Title = "Student ID Card",
                            Type = "LOST"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Bags",
                            ContactEmail = "sam.ortiz@example.edu",
                            ContactName = "Sam Ortiz",
                            DateReported = new DateOnly(2026, 8, 12),
                            Description = "Black backpack with a laptop sleeve and a keychain.",
                            Location = "Main Auditorium",
                            Status = "ACTIVE",
                            Title = "Black Backpack",
                            Type = "FOUND"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Electronics",
                            ContactEmail = "maria.gomez@example.edu",
                            ContactName = "Maria Gomez",
                            DateReported = new DateOnly(2026, 8, 13),
                            Description = "White wireless earbuds in a charging case.",
                            Location = "Lecture Hall",
                            Status = "ACTIVE",
                            Title = "Wireless Earbuds",
                            Type = "LOST"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
